### ISSUE TITLE
随笔

### ISSUE THREAD

**Issue by Junior233** [Junior233/blog_essays#133]
台式机网络配置
```yml
# Let NetworkManager manage all devices on this system
network:
  version: 2
  ethernets:
        wlp4s0:
            dhcp4: false
            addresses: [192.168.31.233/24]
            gateway4: 192.168.31.1
            nameservers:
                    addresses: [114.114.114.114,8.8.8.8,192.168.31.1] 
                    #renderer: NetworkManager
```
注意： addresses, 即dns最好不要把网关【此处为192.168.31.1】填在数组第一的位置。因为运营商的dns解析服务不是很友好。
