### ISSUE TITLE
随笔

### ISSUE THREAD

**Issue by Junior233** [Junior233/blog_essays#229]
给clash设置网易云音乐代理
```
parsers: # array
  - reg: .*
    yaml:
      prepend-rules:
      #  - DOMAIN-SUFFIX,163.com,UnblockNeteaseMusic # rules最前面增加一个规则
        - PROCESS-NAME,NeteaseMusic1,UnblockNeteaseMusic
       # - PROCESS-NAME,WeChat,CuteCloud
    #    - PROCESS-NAME,SunloginClient,CuteCloud
      append-proxies:
        - name: UnblockNeteaseMusic # proxies最后面增加一个服务
          type: http
          server: 127.0.0.1
          port: 18080

```
